# Question 1

In [1]:
import pandas as pd
import datetime as dt
df = pd.read_csv('/Users/pranavaditya/Desktop/Data-Engineering-Journey/Python-Journey/Questions/data.csv')
df['ts']=pd.to_datetime(df['ts'])
filtered = df[(df['ts']>='2025-10-21')&(df['ts']<'2025-10-22')]
filtered['hour']=filtered['ts'].dt.hour
result = filtered.groupby('hour')['seconds'].sum().sort_values(ascending = False).head(5)
result

hour
17    8022
6     7316
21    7034
20    6684
8     6546
Name: seconds, dtype: int64

# Question 2

In [2]:
import re
def common_words(row):
    sentence1 = row['sentence_1']
    sentence2 = row['sentence_2']

    pattern = '\w+'
    lst1 = re.findall(pattern , sentence1)
    lst2 = re.findall(pattern , sentence2)
    st1 = set(lst1)
    st2 = set(lst2)

    result = st1.intersection(st2)

    final_result = {}

    for i in lst2:
        if(i in result):
            if(i in final_result):
                final_result[i]+=1
            else:
                final_result[i]=1

    final_result = dict(sorted(final_result.items()))
    return final_result

df2 = pd.read_csv('/Users/pranavaditya/Desktop/Data-Engineering-Journey/question_02/data.csv')
df2['common_words']=df2.apply(common_words,axis=1)
df2

,sentence_1,sentence_2,common_words
0,Hi I am Rama. I am here only,here only in EY,"{'here': 1, 'only': 1}"
1,Data is the new oil but clean data is gold,"Without clean data, oil becomes useless","{'clean': 1, 'data': 1, 'oil': 1}"
2,Power BI and Tableau are data visualization tools,Power BI connects to multiple sources,"{'BI': 1, 'Power': 1}"
3,Python is great for automation,Automation is the key to productivity,{'is': 1}
4,Practice makes a data analyst perfect,Practice with real datasets makes you perfect,"{'Practice': 1, 'makes': 1, 'perfect': 1}"

# Question 3

In [3]:
import re 

def is_palindrome(check):
    check = check.lower()
    lst = re.findall(r'\w+',check)
    lst = ''.join(lst)
    lst = lst.replace(" ","")

    return lst[::] == lst[::-1]


df3 = pd.read_csv('/Users/pranavaditya/Desktop/Data-Engineering-Journey/question_03/data.csv')
df3['is_palindrome']=df3['text'].apply(is_palindrome)
df3

                           text  is_palindrome
0             No lemon no melon           True
1                 Data Engineer          False
2                       ChatGPT          False
3              Machine Learning          False
4   Was it a car or a cat I saw           True
5                         Civic           True
6             No lemon no melon           True
7                        OpenAI          False
8                         Kayak           True
9              Machine Learning          False
10             Machine Learning          False
11                        Refer           True
12                        Civic           True
13              Step on no pets           True
14  Was it a car or a cat I saw           True
15                        Refer           True
16            Never odd or even           True
17                        Rotor           True
18                        Civic           True
19                        Level           True
20                        Refer           True
21                   Codebasics          False
22    Able was I ere I saw Elba           True
23                        Level           True
24                        Civic           True
25                     Race car           True
26                   Codebasics          False
27                        Rotor           True
28                   Codebasics          False
29                        Stats           True
30              Power BI Report          False
31                       Python          False
32                 n8n Workflow          False
33                      ChatGPT          False
34                      ChatGPT          False
35                       OpenAI          False
36                   Codebasics          False
37                        Kayak           True
38                Data Engineer          False
39                        Stats           True
40            Never odd or even           True
41                        madam           True
42                       OpenAI          False
43            No lemon no melon           True
44                        Civic           True
45               Data Analytics          False
46            No lemon no melon           True
47                    Deep Work          False
48              Step on no pets           True
49                        Stats           True

# Question 4

In [25]:
df4 = pd.read_csv('/Users/pranavaditya/Desktop/Data-Engineering-Journey/question_04/data.csv')
df4

from collections import defaultdict

def freq_chars(df4):
    words = df4['word']
    result = []
    freq = {}
    for word in words:
        for char in word:
            if char in freq:
                freq[char] +=1
            else:
                freq[char] = 1
        result.append({word:freq})
        freq={}
    return result

def is_anagram(lst):

    lst = freq_chars(lst)
    result = defaultdict(list)

    for i in range(0,len(lst)-1):
        dict1_keys  = list(lst[i].keys())
        dict1_keys = dict1_keys[0]

        if not any(dict1_keys in values for values in result.values()):
            result[i].append(dict1_keys)
            for j in range(i+1,len(lst)):
                dict2_keys =  list(lst[j].keys())
                dict2_keys = dict2_keys[0]

                if(len(dict1_keys)!=len(dict2_keys)):
                    continue

                dict1_values = lst[i][dict1_keys]
                dict2_values = lst[j][dict2_keys]
                flag = True

                for val in dict1_values:
                    if(dict1_values.get(val)!=dict2_values.get(val)):
                        flag = False
                        break
                if(flag == True):
                    result[i].append(dict2_keys)
    return dict(result)



final = is_anagram(df4)
df = pd.DataFrame(final.items(),columns = ['group_id','words'])
df['group_length']=len(df['words'])
df

   group_id                                              words  group_length
0         0  [pat, apt, pat, apt, tap, pat, pat, pat, apt, ...             8
1         1  [god, dog, dog, dog, dog, god, dog, dog, god, ...             8
2         2  [rat, art, tar, rat, rat, rat, rat, art, tar, ...             8
3         3  [evil, evil, evil, vile, vile, vile, vile, liv...             8
4         7  [thing, thing, thing, night, night, night, nig...             8
5        11  [bat, tab, bat, bat, bat, bat, bat, tab, tab, ...             8
6        13  [enlist, silent, silent, listen, enlist, silen...             8
7        24  [study, dusty, dusty, study, study, dusty, dus...             8

# Question 5

In [5]:
df5 = pd.read_csv('/Users/pranavaditya/Desktop/Data-Engineering-Journey/question_05/data.csv')
df5


def reverse_word(text):
    lst = list(text)
    i = 0
    j = len(lst)-1
    while(i<j):
        temp = lst[i]
        lst[i] = lst[j]
        lst[j] = temp
        i+=1
        j-=1
    lst = ''.join(lst)
    return lst
    
def reverse_string(lst):
    lst = lst.split(' ')
    result = []
    for i in lst:
        result.append(reverse_word(i))
    return ' '.join(result)

final = reverse_string('Streamlit apps are interactive')

df5['reversed_string']=df5['sentence'].apply(reverse_string)
df5

                             sentence                     reversed_string
0      Streamlit apps are interactive      tilmaertS sppa era evitcaretni
1                    AI is the future                    IA si eht erutuf
2     Pandas is powerful for analysis     sadnaP si lufrewop rof sisylana
3  Power BI connects data beautifully  rewoP IB stcennoc atad yllufituaeb
4      Streamlit apps are interactive      tilmaertS sppa era evitcaretni
5    Analytics drives decision making    scitylanA sevird noisiced gnikam
6  Machine Learning changes the world  enihcaM gninraeL segnahc eht dlrow

# Question 6

In [6]:
from datetime import datetime as dt
import json
import re

df6=pd.read_csv('/Users/pranavaditya/Desktop/Data-Engineering-Journey/question_06/data.csv')
df6

def remove_words_with_digits(text):
      return re.findall(r"\b[A-Za-z]+\b",text)
      
def bucket(time):
    if(time>=dt.strptime('09:00:00', "%H:%M:%S").time() and dt.strptime('10:00:00', "%H:%M:%S").time()>time):
        return '09:00 - 10:00'
    elif(time>=dt.strptime('10:00:00', "%H:%M:%S").time() and dt.strptime('11:00:00', "%H:%M:%S").time()>time):
        return '10:00 - 11:00'
    elif(time>=dt.strptime('11:00:00', "%H:%M:%S").time() and dt.strptime('12:00:00', "%H:%M:%S").time()>time):
        return '11:00 - 12:00'
    elif(time>=dt.strptime('12:00:00', "%H:%M:%S").time() and dt.strptime('13:00:00', "%H:%M:%S").time()>time):
            return '12:00 - 13:00'
    elif(time>=dt.strptime('13:00:00', "%H:%M:%S").time() and dt.strptime('14:00:00', "%H:%M:%S").time()>time):
            return '13:00 - 14:00'
    elif(time>=dt.strptime('14:00:00', "%H:%M:%S").time() and dt.strptime('15:00:00', "%H:%M:%S").time()>time):
            return '14:00 - 15:00'
    elif(time>=dt.strptime('15:00:00', "%H:%M:%S").time() and dt.strptime('16:00:00', "%H:%M:%S").time()>time):
                return '15:00 - 16:00'
        
    
def output(js):
    dict = json.loads(js)
    time  = dt.fromisoformat(dict['timestamp']).time()
    text = dict['text']
    return time , text

def freq_words(lst):
      freq={}
      for i in lst:
            if(i.lower() in freq):
                  freq[i]+=1
            else:
                  freq[i] = 1
      return freq

def sortIt(dic):
      return dict(sorted(dic.items(),key=lambda x :(-x[1],x[0]))[:1])

df6[['time','text']]=df6['json_data'].apply(output).apply(pd.Series)
df6['bucket'] = df6['time'].apply(bucket)

df6= df6.groupby('bucket')['text'].agg(' '.join)
df6=df6.apply(remove_words_with_digits)

df6 = df6.apply(freq_words)
df6.apply(sortIt)

bucket
09:00 - 10:00       {'powerbi': 42}
10:00 - 11:00    {'automation': 39}
11:00 - 12:00       {'powerbi': 45}
12:00 - 13:00        {'stream': 32}
13:00 - 14:00    {'automation': 40}
14:00 - 15:00         {'click': 39}
15:00 - 16:00             {'ai': 3}
Name: text, dtype: object

# Question 7

In [ ]:
import pandas as pd
import numpy as np

df7 = pd.read_csv('/Users/pranavaditya/Desktop/Data-Engineering-Journey/question_07/data.csv')
temp = df7
df7 = df7.rename(columns = {'holding_cost':'holding_rate'})

df7['holding_cost']=df7['holding_rate']*df7['unit_cost']
df7 = df7.groupby('sku').agg({
    'demand':'sum',
    'holding_cost':'mean',
    'order_cost':'mean'
})

df7['demand']=df7['demand']*12
df7['EOQ']=np.sqrt((2*df7['demand']*df7['order_cost'])/df7['holding_cost'])
df7


def simulation(row):

    inventory = row['EOQ']
    demand=row['demand_list']

    stockout = 0
    i = 0
    while(i<180):
        inventory-=demand[i%len(demand)]
        if(inventory<=0):
            lead_time = np.random.randint(2,8)
            remaining = 179-i
            effective  = min(lead_time,remaining)
            stockout+=effective+1

            for j in range(1,effective+1):
                inventory-=demand[(i+j)%len(demand)]
                
            inventory+=row['EOQ']

            i+=effective+1
        else:
            i+=1

    return stockout

temp = temp.groupby('sku')['demand'].agg(list)
df7['demand_list']=temp
final= df7[['EOQ','demand_list']]
final

s = df7.apply(simulation,axis=1)
final['stockout_days']=s
result =  final[['EOQ','stockout_days']]
result

              EOQ  stockout_days
sku
A101   988.690851             22
A102   908.100149             16
B205  1310.772945             23
B207   960.139363             19
C330   744.772395             12
C335   820.140047             20
D410   811.396531             12
E520  1276.896429             15
F615  1464.085175             27
G700  1290.986120             22

# Question 8

In [8]:
df8 = pd.read_csv('/Users/pranavaditya/Desktop/Data-Engineering-Journey/question_08/data.csv')
df8


def z_score(gmv):
    avg = df8['gmv'].mean()
    std = df8['gmv'].std()
    return (gmv-avg)/std

df8['z-score']=df8['gmv'].apply(z_score)
df8 = df8[(df8['z-score'].abs())>2.5]
final = df8[['day','gmv']]
final

            day     gmv
5    2025-01-06  160000
25   2025-01-26   30000
48   2025-02-18  180000
209  2025-07-29  138527